/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FinishUsik: typeof import('./../src/components/FinishUsik.vue')['default']
    Main: typeof import('./../src/components/Main.vue')['default']
    MainUsik: typeof import('./../src/components/MainUsik.vue')['default']
    UniqueUsik: typeof import('./../src/components/UniqueUsik.vue')['default']
  }
}
